local M = {}

M.get = function()
  return {
    Comment = { fg = C.darkgray, italic = true },
    SpecialComment = { fg = C.darkgray, italic = true },
    String = { fg = C.olivegreen },
    Character = { fg = C.olivegreen },
    Number = { fg = C.brown },
    Float = { fg = C.brown },
    Boolean = { fg = C.bluegray },
    Identifier = { fg = C.orange },
    Function = { fg = C.teal },
    Statement = { fg = C.bluegray },
    Conditional = { fg = C.blue },
    Repeat = { fg = C.blue },
    Label = { fg = C.yellow },
    Operator = { fg = C.darkmauve },
    Exception = { fg = C.crimson },
    PreProc = { fg = C.gray },
    Include = { fg = C.darkgray },
    Define = { fg = C.purple },
    Macro = { fg = C.darkgray },
    PreCondit = { fg = C.darkgray },
    StorageClass = { fg = C.purple },
    Structure = { fg = C.yellow },
    Special = { fg = C.brown, italic = true },
    Type = { fg = C.purple },
    TypeDef = { fg = C.purple },
    Underlined = { fg = C.lightblue, underline = true },
    Error = { fg = C.crimson },
    Todo = { fg = C.lightblue, bold = true, italic = true },
    Constant = { fg = C.darkgray },
    Keyword = { fg = C.bluegray },
    Keywords = { fg = C.bluegray },

    -- Neovim
    healthError = { fg = C.red },
    healthSuccess = { fg = C.green },
    healthWarning = { fg = C.yellow },

    --  Diff
    Added = { fg = C.green },
    Changed = { fg = C.orange },
    diffAdded = { fg = C.green },
    diffRemoved = { fg = C.red },
    diffChanged = { fg = C.orange },

    diffFileId = { fg = C.yellow, bold = true, reverse = true },
    diffOldFile = { fg = C.yellow },
    diffNewFile = { fg = C.darkmauve },
    diffFile = { fg = C.darkgray },

    DiffAdd = { fg = C.green },
    DiffChange = { fg = C.orange },
    DiffDelete = { fg = C.red },
    DiffText = { fg = C.yellow },

    debugPc = { bg = C.menu_bg },
    debugBreakpoint = { fg = C.red, reverse = true },

    -- HTML
    htmlArg = { fg = C.orange },
    htmlBold = { fg = C.yellow, bold = true },
    htmlEndTag = { fg = C.lightblue },
    htmlH1 = { fg = C.blue },
    htmlH2 = { fg = C.blue },
    htmlH3 = { fg = C.blue },
    htmlH4 = { fg = C.blue },
    htmlH5 = { fg = C.blue },
    htmlH6 = { fg = C.blue },
    htmlItalic = { fg = C.red, italic = true },
    htmlLink = { fg = C.red, underline = true },
    htmlSpecialChar = { fg = C.lightblue },
    htmlSpecialTagName = { fg = C.yellow },
    htmlTag = { fg = C.lightblue },
    htmlTagN = { fg = C.lightblue },
    htmlTagName = { fg = C.lightblue },
    htmlTitle = { fg = C.white },

    -- Markdown
    markdownBlockquote = { fg = C.yellow, italic = true },
    markdownBold = { fg = C.orange, bold = true },
    markdownCode = { fg = C.orange },
    markdownCodeBlock = { fg = C.orange },
    markdownCodeDelimiter = { fg = C.red },
    markdownH1 = { fg = C.blue, bold = true },
    markdownH2 = { fg = C.blue, bold = true },
    markdownH3 = { fg = C.blue, bold = true },
    markdownH4 = { fg = C.blue, bold = true },
    markdownH5 = { fg = C.blue, bold = true },
    markdownH6 = { fg = C.blue, bold = true },
    markdownHeadingDelimiter = { fg = C.red },
    markdownHeadingRule = { fg = C.darkgray },
    markdownId = { fg = C.orchid },
    markdownIdDeclaration = { fg = C.lightblue },
    markdownIdDelimiter = { fg = C.orchid },
    markdownItalic = { fg = C.yellow, italic = true },
    markdownLinkDelimiter = { fg = C.orchid },
    markdownLinkText = { fg = C.blue },
    markdownListMarker = { fg = C.lightblue },
    markdownOrderedListMarker = { fg = C.red },
    markdownRule = { fg = C.darkgray },

    -- Glyphs
    GlyphPalette1 = { fg = C.red },
    GlyphPalette2 = { fg = C.teal },
    GlyphPalette3 = { fg = C.yellow },
    GlyphPalette4 = { fg = C.blue },
    GlyphPalette6 = { fg = C.teal },
    GlyphPalette7 = { fg = C.fg },
    GlyphPalette9 = { fg = C.red },
  }
end

return M
